version: '3'

services:
    app:
        container_name: fastapi
        build:
            context: .
            dockerfile: ./compose/production/Dockerfile
        volumes:
            - .:/code
            - static_files:/code/static/
        ports:
            - "8000:8000"
        links:
            - "postgresql:postgresql"
        depends_on:
            - postgresql

    postgresql:
        container_name: postgresql
        image: postgres:14
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - pgdata:/var/lib/postgresql/datadb/

    nginx:
        container_name: ngnix
        build:
            context: .
            dockerfile: ./compose/nginx/Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - app:app
        volumes:
            - static_files:/static/
            - ./certificates/:/certificates/
        depends_on:
            - app

volumes:
    pgdata:
    static_files: